{{/* OneChart ingress snippet */}}
{{- define "onechart.ingress" }}
{{- $robustName := include "robustName" .root.Release.Name -}}
{{- $resourceName := $robustName -}}
{{- if .longName }}
{{- $resourceName = printf "%s-%s" $robustName (include "robustName" .ingress.host) -}}
{{- end }}
{{- if .ingress.name }}
{{- $resourceName = include "robustName" .ingress.name -}}
{{- end }}
{{- if .nameSuffix }}
{{- $resourceName = printf "%s-%s" $resourceName (include "robustName" .nameSuffix) -}}
{{- end }}
{{- $svcPort := .root.Values.svcPort -}}
{{- $containerPort := .root.Values.containerPort -}}
{{- $activeServiceName := include "onechart.activeServiceName" .root -}}
{{- $serviceName := $activeServiceName -}}
{{- if .serviceName }}
{{- $serviceName = .serviceName -}}
{{- end }}
{{- $host := .ingress.host -}}
{{- if .host }}
{{- $host = .host -}}
{{- end }}
{{- $tlsHost := $host -}}
{{- if .tlsHost }}
{{- $tlsHost = .tlsHost -}}
{{- end }}
{{- $annotations := .ingress.annotations -}}
{{- if .annotations }}
{{- $annotations = .annotations -}}
{{- end }}
{{- $ingressClassName := .ingress.ingressClassName -}}
{{- if .ingressClassName }}
{{- $ingressClassName = .ingressClassName -}}
{{- end }}
{{- if not $ingressClassName }}
{{- $ingressClassName = "kong" -}}
{{- end }}
{{- $tlsEnabled := default false .ingress.tlsEnabled -}}
{{- if hasKey . "tlsEnabled" }}
{{- $tlsEnabled = .tlsEnabled -}}
{{- end }}
{{- $renderRuleHost := true -}}
{{- if .omitRuleHost }}
{{- $renderRuleHost = false -}}
{{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $resourceName }}
  namespace: {{ .root.Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" .root | nindent 4 }}
  {{- if or (or (or (or .root.Values.gitSha) $annotations) .root.Values.gitRepository) .forceDefaultAnnotations }}
  annotations:
    {{- if $annotations }}
      {{- toYaml $annotations | nindent 4 }}
    {{- else}}
    konghq.com/strip-path: "true"
    konghq.com/https-redirect-status-code: "301"
    konghq.com/protocols: https
    {{- end }}
    {{- if .root.Values.gitSha }}
    unite.as/git-sha: {{ .root.Values.gitSha }}
    {{- end }}
    {{- if .root.Values.gitRepository }}
    unite.as/git-repository: {{ .root.Values.gitRepository }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ $ingressClassName }}
  {{- if $tlsEnabled }}
  tls:
    - hosts:
        - {{ $tlsHost | quote }}
      {{- if not .omitTlsSecretName }}
      secretName: {{ .ingress.secretName | default (printf "tls-%s" $resourceName) }}
      {{- end }}
  {{- end }}
  rules:
    - {{- if $renderRuleHost }}
      host: {{ $host | quote }}
      {{- end }}
      http:
        {{- if not .ingress.paths }}
        paths:
          - path: {{ .ingress.path | default "/" | quote }}
            pathType: {{ .ingress.pathType | default "Prefix" | quote }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ if $svcPort }}{{ $svcPort }}{{ else }}{{ $containerPort }}{{ end }}
        {{- else }}
        paths:
          {{- range .ingress.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" | quote }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ if $svcPort }}{{ $svcPort }}{{ else }}{{ $containerPort }}{{ end }}
          {{- end }}
        {{- end }}
{{- end }}

{{- with .Values.ingress }}
  {{- template "onechart.ingress" (dict "root" $ "ingress" .) }}
  {{- if and $.Values.rollout $.Values.rollout.enabled }}
    {{- $previewServiceName := include "onechart.previewServiceName" $ -}}
    {{- if and $.Values.rollout.blueGreen $.Values.rollout.blueGreen.previewIngress $.Values.rollout.blueGreen.previewIngress.private }}
      {{- template "onechart.ingress" (dict "root" $ "ingress" . "nameSuffix" "preview" "serviceName" $previewServiceName "host" $previewServiceName "tlsHost" $previewServiceName "ingressClassName" "tailscale" "annotations" (dict "tailscale.com/hostname" $previewServiceName "tailscale.com/http-redirect" "true") "tlsEnabled" true "omitTlsSecretName" true "omitRuleHost" true) }}
    {{- else }}
      {{- template "onechart.ingress" (dict "root" $ "ingress" . "nameSuffix" "preview" "serviceName" $previewServiceName "host" (regexReplaceAll "^[^.]*" .host $previewServiceName) "forceDefaultAnnotations" true) }}
    {{- end }}
  {{- end }}
{{- end }}

{{- range .Values.ingresses }}
{{template "onechart.ingress" (dict "root" $ "ingress" . "longName" true) }}
{{- end }}
