{{- define "common.container.tpl" -}}
name: {{ template "robustName" .Release.Name }}
{{- if .Values.securityContext }}
securityContext:
  runAsNonRoot: {{ hasKey .Values.securityContext "runAsNonRoot" | ternary .Values.securityContext.runAsNonRoot true }}
  runAsUser: {{ hasKey .Values.securityContext "runAsUser" | ternary .Values.securityContext.runAsUser 621 }}
  readOnlyRootFilesystem: {{ hasKey .Values.securityContext "readOnlyRootFilesystem" | ternary .Values.securityContext.readOnlyRootFilesystem true }}
  allowPrivilegeEscalation: {{ hasKey .Values.securityContext "allowPrivilegeEscalation" | ternary .Values.securityContext.allowPrivilegeEscalation false }}
  {{- range $key, $value := .Values.securityContext }}
  {{- if not (or (eq $key "runAsNonRoot") (eq $key "runAsUser") (eq $key "readOnlyRootFilesystem") (eq $key "allowPrivilegeEscalation")) }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
{{- else }}
securityContext:
  runAsNonRoot: true
  runAsUser: 621
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
{{- end }}
image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.command }}
command:
  - {{ .Values.shell }}
  - -c
  - {{ .Values.command | quote }}
{{- end }}
ports:
  {{- if not .Values.ports }}
  - name: http
    containerPort: {{ .Values.containerPort }}
    protocol: TCP
  {{- else }}
  {{- range .Values.ports }}
  - name: {{ .name }}
    containerPort: {{ .containerPort }}
    protocol: TCP
  {{- end }}
  {{- end }}
{{- if .Values.probe.enabled }}
readinessProbe:
  httpGet:
    path: {{ .Values.probe.path }}
    port: {{ .Values.containerPort }}
    scheme: HTTP
  {{- with .Values.probe.settings }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- if .Values.livenessProbe.enabled }}
livenessProbe:
  httpGet:
    path: {{ .Values.livenessProbe.path }}
    port: {{ .Values.containerPort }}
    scheme: HTTP
  {{- with .Values.livenessProbe.settings }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- if not .Values.resources.ignore }}
resources:
  {{- if .Values.resources.ignoreLimits }}
  requests:
    {{- toYaml .Values.resources.requests | nindent 4 }}
  {{- else }}
    {{- toYaml .Values.resources | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
